### ISSUE TITLE
NullPointerException at DeserializerBuilder.isJsonValueEvent(DeserializerBuilder.java:174)

### ISSUE THREAD

**Issue by wizzardo** [eclipse-ee4j/yasson#101]
```
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.yasson.internal.serializer.DeserializerBuilder.isJsonValueEvent(DeserializerBuilder.java:174)
	at org.eclipse.yasson.internal.serializer.DeserializerBuilder.build(DeserializerBuilder.java:123)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:56)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:50)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:45)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:52)
```

```
    public static class StringHolder {
        public String value;
    }

    public static void main(String[] args) throws IOException {
        Jsonb jsonb = JsonbBuilder.create();
        Object items = jsonb.fromJson("{\"value\":\"qwerty\"}", StringHolder.class);
        String result = jsonb.toJson(items);
        System.out.println(result);
    }
```

**Comment by Verdent** [comment]
I have tested it against the master and looks like it is fixed now.
