### ISSUE TITLE
module-info.java needs to declare dependency on java.sql

### ISSUE THREAD

**Issue by cayhorstmann** [eclipse-ee4j/yasson#121]
I put yasson.jar on the module path. When serializing, you use java.sql.Date somewhere. This is the exception I get:

`Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/Date
	at org.eclipse.yasson/org.eclipse.yasson.internal.serializer.DefaultSerializers.initSerializers(DefaultSerializers.java:77)
	at org.eclipse.yasson/org.eclipse.yasson.internal.serializer.DefaultSerializers.<init>(DefaultSerializers.java:61)
	at org.eclipse.yasson/org.eclipse.yasson.internal.serializer.DefaultSerializers.<clinit>(DefaultSerializers.java:54)
	at org.eclipse.yasson/org.eclipse.yasson.internal.model.PropertyModel.resolveCachedSerializer(PropertyModel.java:112)
	at org.eclipse.yasson/org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:90)
	at org.eclipse.yasson/org.eclipse.yasson.internal.model.customization.ordering.PropertyOrdering.lambda$orderProperties$0(PropertyOrdering.java:79)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1680)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.eclipse.yasson/org.eclipse.yasson.internal.model.customization.ordering.PropertyOrdering.orderProperties(PropertyOrdering.java:80)
	at org.eclipse.yasson/org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:63)
	at org.eclipse.yasson/org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:56)
	at org.eclipse.yasson/org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:37)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1719)
	at org.eclipse.yasson/org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:103)
	at org.eclipse.yasson/org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:75)
	at org.eclipse.yasson/org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at ch15.sec06/com.horstmann.places.Demo4.main(Demo4.java:28)
Caused by: java.lang.ClassNotFoundException: java.sql.Date
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 22 more`

Adding `requires java.sql;` to `module-info.java` makes it work.

**Comment by Verdent** [comment]
Hi @cayhorstmann ,
Thank you for reporting this. I will fix this issue now.

**Comment by Verdent** [comment]
I am closing this issue because of it is fixed now in master.
