### ISSUE TITLE
Runtime failure on JSON serialization of object with Optional getter.

### ISSUE THREAD

**Issue by dwaite** [eclipse-ee4j/yasson#125]
The following test program fails; when the nullable field is a non-null value. I believe this is due to the type being inferred from the field and not the (actually used) getter/setter.

```java ScratchPad.java
import java.net.MalformedURLException;
import java.util.Optional;

import javax.json.bind.Jsonb;
import javax.json.bind.JsonbConfig;
import javax.json.bind.config.BinaryDataStrategy;
import javax.json.bind.spi.JsonbProvider;

public class ScratchPad {

	public static class Foo {
		private String bar;
		public void setBar(String value) {
			bar = value;
		}
		public Optional<String> getBar() {
			return Optional.ofNullable(bar);
		}
	}
	public static void main(String[] args) throws MalformedURLException {
		
		JsonbConfig config = new JsonbConfig();
		config = config
			.withBinaryDataStrategy(BinaryDataStrategy.BASE_64_URL)
			.withFormatting(true)
			.withStrictIJSON(true);
		Jsonb jsonb = JsonbProvider.provider().create().withConfig(config).build();
		jsonb.toJson(new Foo());
		Foo foo = new Foo(); // Works: {}
		foo.setBar("bar");
		jsonb.toJson(foo); // Fails: 
		//		Exception in thread "main" java.lang.ClassCastException: java.util.Optional cannot be cast to java.lang.String
		//		at org.eclipse.yasson.internal.serializer.StringTypeSerializer.serialize(StringTypeSerializer.java:32)
		//		at org.eclipse.yasson.internal.serializer.AbstractValueTypeSerializer.serialize(AbstractValueTypeSerializer.java:51)
	}
}

**Comment by dwaite** [comment]
Tested against current 1.0.2-SNAPSHOT

**Comment by dwaite** [comment]
Adding a PropertyVisibilityStrategy that returns true for fields and false for methods lets the document serialize properly, which gives me a temporary workaround.

**Comment by Verdent** [comment]
Fixed in master.

**Comment by dwaite** [comment]
Is there a 1.0.2 release planned soon which would have this fix?
