### ISSUE TITLE
NullPointerException during serialization

### ISSUE THREAD

**Issue by ThomasSousa96** [eclipse-ee4j/yasson#138]
```
 java.lang.NullPointerException
 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:104)
 	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)
 	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
 	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:121)
 	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:77)
 	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
 	at org.glassfish.jersey.jsonb.internal.JsonBindingProvider.writeTo(JsonBindingProvider.java:118)
 	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
 	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
 	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
 	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
 	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
 	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
 	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
 	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1137)
 	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
 	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
 	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:280)
 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)
 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
 	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1622)
 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)
 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
 	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
 	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:593)
 	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
 	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
 	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
 	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
 	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
 	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ThomasSousa96** [comment]
The problem occur when try serialize an direct instance of Object class.

```
Jsonb jsonb = JsonbBuilder.create();
String json = jsonb.toJson(new Object());
```

The problem root:
```
org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(Class<?>)
```

```
 public ClassModel getOrCreateClassModel(Class<?> clazz) {
       //clazz = java.lang.Object
        ClassModel classModel = classes.get(clazz);
        //classModel == null
        if (classModel != null) {
            return classModel;
        }
        final Stack<Class> newClassModels = new Stack<>();
        //Never will enter in the for statement
        for (Class classToParse = clazz; classToParse != Object.class; classToParse = classToParse.getSuperclass()) {
            newClassModels.push(classToParse);
        }

        ClassModel parentClassModel = null;
        //newClassModels will be empty 
        while (!newClassModels.empty()) {
            Class toParse = newClassModels.pop();
            parentClassModel = classes.computeIfAbsent(toParse, new ParseClassModelFunction(parentClassModel, classParser, jsonbContext));
        }
        //The cache map will return null 
        return classes.get(clazz);
    }
```
