### ISSUE TITLE
Serialization fails with 2 type parameters

### ISSUE THREAD

**Issue by flaviocosta-net** [eclipse-ee4j/yasson#140]
I see that #61 fixed an issue with generics, but that doesn't seem to be of help in a case a class has two type parameters.

I have a `Container<D, C>` interface which, when I try to serialize, produces the error `Generic bound not found for type C declared in my.package.Container<?, ?>`.

The type C is used in a method declaration of the interface:
`public List<C> getComponents();`

The current implementation seems to use `((ParameterizedType) getRuntimeType()).getActualTypeArguments()[0]`, which will obviously only take the first type argument in consideration.

This implementation could rather use `((Class<?>) superClassType.getRawType()).getTypeParameters()` to identify the names of each argument (in this case, D and C) and then use its position/index to determine which element returned by getActualTypeArguments() that should be used.

**Comment by flaviocosta-net** [comment]
```
java.lang.IllegalStateException: Generic bound not found for type C declared in my.package.Container<?, ?>.
	at org.eclipse.yasson.internal.ReflectionUtils.resolveTypeArguments(ReflectionUtils.java:166)
	at org.eclipse.yasson.internal.ReflectionUtils.resolveType(ReflectionUtils.java:109)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:88)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:76)
	at org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:35)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:91)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:92)
```

**Comment by Verdent** [comment]
Hi @flaviocosta-net, could you please provide reproducer for this issue?

**Comment by bravehorsie** [comment]
@flaviocosta-net 

> The current implementation seems to use ((ParameterizedType) getRuntimeType()).getActualTypeArguments()[0], which will obviously only take the first type argument in consideration.

It is not how it looks :) getActualTypeArguments()[0] in CollectionDeserializer is resolving generic type for the List which has always only one parameter type, hence the hardcoded `[0]`.

What you are probably missing is passing the runtime type to jsonb runtime. See methods `toJson(..)` which are picking `Type runtimeType` parameter, [for example this](https://github.com/eclipse-ee4j/jsonb-api/blob/851e55c5ca70a235560fc48aca057459e9edff15/api/src/main/java/javax/json/bind/Jsonb.java#L274).

**Comment by bravehorsie** [comment]
a PR attaches a test that demonstrates serialization of generic types without providing generic information.

**Comment by NeerajSachdeva** [comment]
I'd my class structure like this MyBlahBlahClass<T, K> & was getting errors like below
[12/16/20 11:18:57:960 EST] 00000134 org.eclipse.yasson.internal.ReflectionUtils W Generic bound not found for type K declared in class com.MyBlahBlahClass
[12/16/20 11:18:57:960 EST] 00000134 org.eclipse.yasson.internal.ReflectionUtils W Generic bound not found for type T declared in class com.MyBlahBlahClass

I got rid of it like this

      String json =
          JsonbBuilder.create().toJson(myResponseObject, new ArrayList<MyBlahBlahClass<String, String>>() {}.getClass().getGenericSuperclass());
