### ISSUE TITLE
yasson-jar-file can not be analyzed with jdeps

### ISSUE THREAD

**Issue by JochenHiller** [eclipse-ee4j/yasson#143]
I tried to check dependencies to JavaSE compact profiles for Yasson by running

`jdeps -P yasson-1.0.1.jar`

downloaded from MavenCentral at http://search.maven.org/#artifactdetails%7Corg.eclipse%7Cyasson%7C1.0.1%7Cjar
I am using JavaSE 8u144.

I got:

```
jdeps -P yasson-1.0.1.jar
Exception in thread "main" java.lang.InternalError: Missing message: warn.skipped.entry
	at com.sun.tools.jdeps.JdepsTask.getMessage(JdepsTask.java:709)
	at com.sun.tools.jdeps.JdepsTask.warning(JdepsTask.java:673)
	at com.sun.tools.jdeps.JdepsTask.findDependencies(JdepsTask.java:563)
	at com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:324)
	at com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:306)
	at com.sun.tools.jdeps.Main.main(Main.java:48)
```

This seems to be related to JDK bug https://bugs.openjdk.java.net/browse/JDK-8167014, which stated the JAR file as "invalid".

I re-run the same with jdeps from JavaSE 9 (build 9+181) I got this message:

```
jdeps -P yasson-1.0.1.jar
Exception in thread "main" java.lang.module.FindException: Module java.json.bind not found, required by org.eclipse.yasson
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:889)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:357)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:187)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration.<init>(JdepsConfiguration.java:121)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration.<init>(JdepsConfiguration.java:69)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:596)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:584)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:535)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:511)
	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```
	
Same issue with previous versions from MavenCentral.

For JavaSE 8: If I unjar the file, modify a file (MANIFEST.MF) and jar under new filename, everything does work.
(BTW: It will be marked to need Full-JRE profile due to java.beans usage).

For JaveSE 9: I will get same error message for this re-built JAR file.

Can you check how you build the JAR file? I expect that jdeps should always work on a JAR file.
(BTW: I have more troubles processing yasson-jar-file in bnd, where I am not sure if this has the same root cause).

**Comment by JochenHiller** [comment]
BTW: I ran into the same issue with the JAR file from Glassfish and JSON-P:
See JAR file from http://search.maven.org/#artifactdetails%7Corg.glassfish%7Cjavax.json%7C1.1.2%7Cbundle

Same errors on jdeps 8 and jdeps 9.

**Comment by bravehorsie** [comment]
This is because of [JPMS module descriptor](https://github.com/eclipse-ee4j/yasson/blob/master/src/main/java/module-info.java) inside yasson.
jdeps can't check all dependencies because it is missing dependency jars of yasson. This module descriptor references to jsonb-api and jsonp-api which are not part of Yasson's jar. If I download them both and add to module path:

`jdeps --module-path javax.json.bind-api-1.0.jar:javax.json-api-1.1.3.jar yasson-1.0.1.jar`

Dependencies of Yasson are properly printed to output.
