### ISSUE TITLE
Attribute java.util.Date without time in format throws exception related to Date-Time API

### ISSUE THREAD

**Issue by Tibor17** [eclipse-ee4j/yasson#149]
I have observed exception while serializing DTO with `java.util.Date` (yyyy-MM-dd):
`java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor: {},ISO,UTC resolved to 2000-12-31 of type java.time.format.Parsed`
`Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds`

I am using `org.eclipse:yasson:1.0.1` and `org.glassfish:javax.json:1.1.2`.
I have this code:
```
person.birth = new SimpleDateFormat("yyyy-MM-dd").parse("2001-01-01");
Jsonb jsonb = JsonbBuilder.create();
String personJson = jsonb.toJson(person);
```
and the annotation bindings on `java.util.Date`:
```
@JsonbDateFormat("yyyy-MM-dd")
public Date birth;
```

**Comment by Tibor17** [comment]
java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor: {},ISO,UTC resolved to 2000-12-31 of type java.time.format.Parsed
	at java.time.Instant.from(Instant.java:378)
	at org.eclipse.yasson.internal.serializer.DateTypeDeserializer.parseWithFormatter(DateTypeDeserializer.java:56)
	at org.eclipse.yasson.internal.serializer.DateTypeDeserializer.parseWithFormatter(DateTypeDeserializer.java:29)
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeDeserializer.parseWithFormatterInternal(AbstractDateTimeDeserializer.java:122)
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeDeserializer.deserialize(AbstractDateTimeDeserializer.java:56)
	at org.eclipse.yasson.internal.serializer.AbstractValueTypeDeserializer.deserialize(AbstractValueTypeDeserializer.java:64)
	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.deserializeNext(ObjectDeserializer.java:165)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:85)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:61)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:57)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:50)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:45)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:52)
	at PolymorphismTest.shouldMatchChicken(PolymorphismTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds
	at java.time.format.Parsed.getLong(Parsed.java:203)
	at java.time.Instant.from(Instant.java:373)
	... 40 more

In class `java.time.format.Parsed`:
```
    @Override
    public long getLong(TemporalField field) {
        Objects.requireNonNull(field, "field");
        Long value = fieldValues.get(field);
        if (value != null) {
            return value;
        }
        if (date != null && date.isSupported(field)) {
            return date.getLong(field);
        }
        if (time != null && time.isSupported(field)) {
            return time.getLong(field);
        }
        if (field instanceof ChronoField) {
            throw new UnsupportedTemporalTypeException("Unsupported field: " + field);
        }
        return field.getFrom(this);
    }
```

**Comment by Tibor17** [comment]
Why the `java.util.Date` is processed by Java Date Time API.
Do you have unit tests with dates asserting expected values?

**Comment by Verdent** [comment]
Hi @Tibor17,
I have tested this issue you are reporting and could not reproduce this exception against the master. This issue should not occur in the future release.

**Comment by bravehorsie** [comment]
@Tibor17 even java.util.Date is an time instant which by definition needs a time zone and time part to be parsed. In order to create instant from "2001-01-01" string you need to say what time zone you like to parse it into. When you parse this with `java.util.SimpleDateFormat` you will get an instant in a default timezone on the host where you are running. If we do the same in Yasson than for example the same REST request would be parsed differently depending on the host settings. Throwing exception by default in this case may seem user unfriendly but is preventing from shooting yourself into leg accidentally and is the same what java 8 Date/Time API does.

To your question _why `java.util.Date` is parsed by Java Date Time API._
This is required by jsonb specification. See [@JsonbDateFormat javadoc](https://github.com/eclipse-ee4j/jsonb-api/blob/851e55c5ca70a235560fc48aca057459e9edff15/api/src/main/java/javax/json/bind/annotation/JsonbDateFormat.java#L27).

**Comment by bravehorsie** [comment]
Duplicates https://github.com/eclipse-ee4j/yasson/issues/162
