### ISSUE TITLE
Error serializing JPA entity with uninitialized properties (Hibernate)

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/yasson#150]
Hibernate throws a `LazyInitializationException` when an uninitialized property is accessed outside an open session. Yasson doesn't handle the situation of such uninitialized properties and propagates the error:

```
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: eu.ggam.contabilidad.core.entity.MovimientoLectura.etiquetas, could not initialize proxy - no Session
	at org.hibernate@5.3.1.Final//org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:589)
	at org.hibernate@5.3.1.Final//org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:208)
	at org.hibernate@5.3.1.Final//org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:568)
	at org.hibernate@5.3.1.Final//org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:139)
	at org.hibernate@5.3.1.Final//org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:48)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:30)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:103)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:119)
	at org.eclipse.yasson//org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:75)
	at org.eclipse.yasson//org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
```

EclipseLink works correctly. I understand Hibernate specifics are out of control for Yasson, but I wonder if it could check `Persistence.getPersistenceUtil.isLoaded(entity, field)` before trying to serialize fields.

**Comment by ggam** [comment]
As a workaround, I've created the following entity listener that sets `null` on uninitialized properties:
```
public class UninitializedProxiesListener {

    @PersistenceContext
    private EntityManager em;

    @PostLoad
    public void clearUninitialized(Object entity) throws IllegalArgumentException, IllegalAccessException {
        PersistenceUtil persistenceUtil = Persistence.getPersistenceUtil();
        EntityType<? extends Object> entityType = em.getMetamodel().entity(entity.getClass());

        for (Attribute<? extends Object, ?> attribute : entityType.getAttributes()) {
            String name = attribute.getName();
            if (!persistenceUtil.isLoaded(entity, name)) {
                Member javaMember = attribute.getJavaMember();
                if (javaMember instanceof Field) {
                    Field field = (Field) javaMember;
                    field.setAccessible(true);
                    field.set(entity, null);
                }
            }
        }
    }
}
```

Hibernate will detect the changes and will perform an `UPDATE` statement. In order to avoid that, you have to set the `org.hibernate.readOnly` query hint to `true`. For example:
```
@NamedQuery(
    name = "....",
    query = "....",
    hints = @QueryHint(name = "org.hibernate.readOnly", value = "true")
)
```

**Comment by bravehorsie** [comment]
Yasson does not have a dependency to JPA API to work with it. What should be done here is wrapping any exception thrown from runtime with JsonbException.

**Comment by ggam** [comment]
The problem is that the exception doesn't really mean a problem there. By default, Hibernate throws a LazyInstantiationException when you try to get a property that hasn't been loaded, and it can't load it. That is Hibernate specific behavior and Yasson has nothing to do with it.

The problem is, Yasson tries to read all the properties and, as expected, treats an exception like an error. But in this particular case, that exception just means that there's no value to return to you. In other words, fpr Yasson, that LazyInstantiationException is like a null.

Now, obviously Yasson doesn't care about such vendor specific behavior and can't treat some exceptions in an specific manner. But calling Persistence.getPersistenceUtil.isLoaded(entity, field) as I proposed effectively prevents that exception.

Neither JSON-B nor Yasson have a JPA dependency and that should stay that way. But this is easy to solve with a bit of reflection, verifying whether a JPA provider is present. A "requires static" clause would need to be added for it to work on the module path.

But thinking about this a bit more, I'm seeing that it's not so simple. The property might have a default value or the user might have set it, but the JPA check would still return false.

Since WildfFly uses Hibernate and Yasson, I'll verify there if this problem exists and open an issue on their tracker. I will also have a look at how JAX-B RI handles these cases.

**Comment by bravehorsie** [comment]
> The problem is, Yasson tries to read all the properties and, as expected, treats an exception like an error. But in this particular case, that exception just means that there's no value to return to you. In other words, fpr Yasson, that LazyInstantiationException is like a null.

Yasson doesn't try to read anything by itself, the user does. In case of accessing detached JPA objects  the problem is obviously elsewhere and Yasson doesn't and should not have any clue about it. This is similar to access a network resource in a property getter, if something doesn't work Yasson should propagate the exception and not treat it as null.

**Comment by bravehorsie** [comment]
Closing this for its inactivity.
