### ISSUE TITLE
Error getting value when using lambda expressions

### ISSUE THREAD

**Issue by ahmadshahwan** [eclipse-ee4j/yasson#194]
When the serialized object is created using lambda expression, a `JsonbException` with a message of the sort "Error getting value on: com.acme.Entry$$Lambda$40/0x00000008000f7040@45018215" is thrown.

The following code:
```java
package com.acme;

import javax.json.bind.Jsonb;
import javax.json.bind.JsonbBuilder;

public class Entry {

    public interface Cat {
        String getName();
    }
    
    public static void main(String args[]) {
        Jsonb jsonb = JsonbBuilder.create();
        Cat cat = () -> "Catie";
        jsonb.toJson(cat);
    }
}
```

Results in the following stack trace:
```
SEVERE: Generating incomplete JSON
Exception in thread "main" javax.json.bind.JsonbException: Error getting value on: com.acme.Entry$$Lambda$40/0x00000008000f7040@2928854b
	at org.eclipse.yasson.internal.model.GetValueCommand.getValue(GetValueCommand.java:36)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:72)
	at org.eclipse.yasson.internal.model.PropertyModel.getValue(PropertyModel.java:257)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:76)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:60)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:118)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at com.acme.Entry.main(Entry.java:15)
Caused by: java.lang.IllegalAccessException: class org.eclipse.yasson.internal.model.GetFromGetter cannot access a member of class com.acme.Entry$$Lambda$40/0x00000008000f7040 with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at org.eclipse.yasson.internal.model.GetFromGetter.internalGetValue(GetFromGetter.java:28)
	at org.eclipse.yasson.internal.model.GetValueCommand.getValue(GetValueCommand.java:34)
	... 9 more
```

Replacing the lambda expression with an anonymous class solves the issue. However, both expressions are supposed to be equivalent, and many IDEs suggest the shortening of anonymous classes into lambdas systematically.

**Comment by ahmadshahwan** [comment]
Thanks Andrew, I'm on it.
