### ISSUE TITLE
Custom adapters of type T do not also apply to Optional<T>

### ISSUE THREAD

**Issue by aguibert** [eclipse-ee4j/yasson#309]
If I register a JsonbAdapter for a type T, it will not be correctly applied to properties of type Optional<T> upon serialization. For example:

### Adapter class:
```java
public class ThrowableAdapter implements JsonbAdapter<Throwable, Map<String, Object>> {

  @Override
  public Map<String, Object> adaptToJson(Throwable obj) throws Exception {
    HashMap<String, Object> output = new HashMap<>();
    output.put("message", obj.getMessage());
    output.put("type", obj.getClass().getName());

    return unmodifiableMap(output);
  }

  @Override
  public Throwable adaptFromJson(Map<String, Object> obj) throws Exception {
    throw new UnsupportedOperationException("not implemented");
  }
}
```

### Property class:
```java
public class ValueClass {

  public Instant getStartedAt() { ... }

  public Optional<Instant> getFinishedAt() { ... }

  public Optional<Throwable> getException() { ... }

  // setters ....
}
```

If we attempt to serialize an object of type `ValueClass` like this:
```java
public class JsonbTypeAdapterTest {

  private final JsonbConfig config = new JsonbConfig()
      .withAdapters(
          new ThrowableAdapter()
      )
      .withFormatting(true);

  private final Jsonb jsonb = JsonbBuilder.newBuilder()
      .withConfig(config)
      .build();

  @Test
  public void testTypeAdapter() {
    ValueClass obj = new ValueClass();
    obj.setStartedAt(Instant.now());
    obj.setException(new RuntimeException("hit me"));
    
    String toJson = jsonb.toJson(obj); // fails with ClassCastException
  }
}
```

### Stack trace:
```
javax.json.bind.JsonbException: Unable to serialize property 'exception' from org.example.testcase.jsonbtypeadapter.ValueClass
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:68)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:148)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:102)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:118)
	at org.example.testcase.jsonbtypeadapter.JsonbTypeAdapterTest.testTypeAdapter(JsonbTypeAdapterTest.java:31)
Caused by: javax.json.bind.JsonbException: Problem adapting object of type class java.lang.Throwable to java.util.Map<java.lang.String, java.lang.Object> in class class org.example.testcase.jsonbtypeadapter.ThrowableAdapter
	at org.eclipse.yasson.internal.serializer.AdaptedObjectSerializer.serialize(AdaptedObjectSerializer.java:72)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:100)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:66)
	... 24 more
Caused by: java.lang.ClassCastException: java.util.Optional incompatible with java.lang.Throwable
	at java.base/java.lang.ClassCastException.<init>(ClassCastException.java:71)
	at org.example.testcase.jsonbtypeadapter.ThrowableAdapter.adaptToJson(ThrowableAdapter.java:9)
	at org.eclipse.yasson.internal.serializer.AdaptedObjectSerializer.serialize(AdaptedObjectSerializer.java:61)
	... 27 more
```

**Comment by aguibert** [comment]
After investigating this more I realized that it has to do with a little more than just the getter methods on the JSON model class. This occurs when there is a field of the same name as a getter, but with different types, for example:
```java
public class ValueClass {
   
  private Throwable exception;

  public Optional<Throwable> getException() { ... }
}
```

**Comment by bmhm** [comment]
Good finding! Actually, in my real application, I was using Immutables (https://github.com/immutables/immutables), i.e. a generated class. It indeed uses `@Nullable Throwable exception` internally, because Optional should of course never be used in a field.

That's omnited in the example from https://github.com/eclipse-ee4j/yasson/issues/309#issue-483521080, but does it still produce the same error?

**Comment by aguibert** [comment]
hi @bmhm, yes I was able to reproduce the issue with the generated class, and after attaching a debugger I realized that the root issue was the property field and corresponding getter method having different Java types.

I expect to have a PR soon which you could use to confirm the fix.
