### ISSUE TITLE
Improve Exception message when default constructor is missing

### ISSUE THREAD

**Issue by Simulant87** [eclipse-ee4j/yasson#316]
Caused by this issue https://github.com/quarkusio/quarkus/issues/3179 

```
Caused by: javax.json.bind.JsonbException: Internal error: null
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:76)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:56)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:53)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:93)
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:66)
	... 98 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.eclipse.yasson.internal.ReflectionUtils.createNoArgConstructorInstance(ReflectionUtils.java:201)
	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.getInstance(ObjectDeserializer.java:94)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:61)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:70)
	... 102 more
```

I would like to improve the Message of the Exception when a default constructor is missing.
I would put an additional null check into ObjectDeserializer#getInstance and throw an Exception when the constructor is not present containing the name of the class so a user knows the affected class and how to fix the issue.

As I said, I would like to provide a fix by myself in the following days.

**Comment by Simulant87** [comment]
I closed the ticket, as the merge request containing the enhancement is merged.
