### ISSUE TITLE
Cannot serialize objects with java.nio.file.Path

### ISSUE THREAD

**Issue by rdehuyss** [eclipse-ee4j/yasson#419]
**Describe the bug**
```
Caused by: java.lang.IllegalAccessException: class org.eclipse.yasson.internal.model.ReflectionPropagation cannot access a member of class sun.nio.fs.UnixPath (in module java.base) with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.lambda$acceptMethod$0(ReflectionPropagation.java:51)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:110)
	... 101 more
```

**To Reproduce**
See failing unit test:
```
package org.jobrunr.utils.mapper;

import org.junit.jupiter.api.Test;

import javax.json.bind.JsonbBuilder;
import java.nio.file.Path;

public class YassonPathTest {

    @Test
    public void serializeObjectWithPath() {
        final ObjectWithPath objectWithPath = new ObjectWithPath(Path.of("/tmp"));
        final String s = JsonbBuilder.create().toJson(objectWithPath);
    }

    public static class ObjectWithPath {
        private Path path;

        public ObjectWithPath(Path path) {
            this.path = path;
        }

        public Path getPath() {
            return path;
        }

        public void setPath(Path path) {
            this.path = path;
        }
    }
}

```

**Expected behavior**
To have the path serialized in the json

**System information:**
 - OS: Ubuntu 19.10
 - Java Version: 11
 - Yasson Version: 1.0.7

**Additional context**

**Comment by aguibert** [comment]
Thanks for opening this issue @rdehuyss, I'm going to swap it from [bug] to [enhancement] since the JSON-B spec does not mandate support for `java.nio.file.Path` (I still think it will be good to support though).

**Comment by rwperrott** [comment]
That's annoying, I'll have to implement a JsonbAdapter<Path,String> for my own project.

**Comment by aguibert** [comment]
hi @rwperrott, I am having a new team member work on this one now actually. Should be available soon in Yasson
