### ISSUE TITLE
module-info.java does not require java.xml directly

### ISSUE THREAD

**Issue by tomsontom** [eclipse-ee4j/yasson#490]
I've tried to use yasson in a project where I also use jlink to build a custom JRE. Looking the at the runtime dependencies of yasson it only requires:
* jakarta.json
* jakarta.json.bind
* java.logging

as the other requires are defined as static. Building an image and launch although leads to the following error
```
Started application
May 18, 2021 12:53:01 PM org.eclipse.yasson.internal.Marshaller marshall
SCHWERWIEGEND: Generating incomplete JSON
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/datatype/XMLGregorianCalendar
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.serializer.DefaultSerializers.initSerializers(DefaultSerializers.java:143)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.serializer.DefaultSerializers.<clinit>(DefaultSerializers.java:57)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.AnnotationIntrospector.collectAnnotations(AnnotationIntrospector.java:763)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:90)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:81)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.Marshaller.getRootSerializer(Marshaller.java:161)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:142)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:73)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:101)
        at org.eclipse.yasson@2.0.2/org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:126)
....
```
The problem is caused because `java.desktop` and `java.sql` transitively require `java.xml` so even linking in `javax.xml` does not help because the yasson module is not going to find the classes in `java.xml` unless the static module is there. 

My current fix is to link in `java.desktop` - I have no idea why `java.sql` does not work - but ideally I can get rid of those extra bits.

I tested with a modified `module-info.java` that adding a `requires java.xml` fixes the problem.

One could naturally argue now that `java.xml` should be required static and one would handle the CNF gracefully in `DefaultSerializers` because if this (de)serializer is used the user anyways has to have him/her self a runtime dependency on `java.xml`. 

I'll provide a PR and this can be discussed there.

**Comment by Verdent** [comment]
Hi Tom,
I do agree that this should be optional similarly to java.sql. Thank you for proposed solution. :-) Could you please change it a bit to register deserializers and serializers of XMLGregorianCalendar similarly to as it is done for java.sql.Date?

**Comment by tomsontom** [comment]
sure - I'll take a look tomorrow and update the PR

**Comment by Verdent** [comment]
Great! Thank you for quick response and sorry for unexcusable delay from my side.

**Comment by tomsontom** [comment]
As I maintain multiple OSS-Projects myself beside the company duties I'm assigned on you don't have to excuse for not directly following up.

**Comment by tomsontom** [comment]
I applied the java.sql strategy and made the java.xml dependency static
