### ISSUE TITLE
Deserialization of Map key with backslash fails

### ISSUE THREAD

**Issue by jakobbraun** [eclipse-ee4j/yasson#540]
**Describe the bug**
When deserializing a Map with a key containing a `\` an exception is thrown.

**To Reproduce**

```java
@Test
void test() throws Exception {
    final Map<String, String> x = Map.of("test\\pom.xml", "hallo");
    final String json = toJson(x);
    System.out.println("json: " + json);
    System.out.println(fromJson(json));
}

private String toJson(final Map<String, String> x) throws Exception {
    try (final Jsonb jsonb = JsonbBuilder.create()) {
        return jsonb.toJson(x);
    }
}

private Map fromJson(final String json) throws Exception {
    try (final Jsonb jsonb = JsonbBuilder.create()) {
        return jsonb.fromJson(json, Map.class);
    }
}
```

For me this code fails with:

```
jakarta.json.bind.JsonbException: Unable to deserialize property 'test\pom.xml' because of: Internal error: Unexpected char 112 at (line no=1, column no=7, offset=6)

	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:100)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:64)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:62)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:66)
	at Test.java:57
```

**Expected behavior**

Deserialization works fine.

**System information:**
 - OS: Linux
 - Java Version: 11
 - Yasson Version: 2.0.4
 - jakarta.json.bind-api version: 2.0.0

**Comment by Verdent** [comment]
I do not think, this is Yasson issue. This exception is caused by JSON-P implementation.
```
Caused by: jakarta.json.stream.JsonParsingException: Unexpected char 112 at (line no=1, column no=7, offset=6)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:577)
	at org.glassfish.json.JsonTokenizer.unescape(JsonTokenizer.java:207)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:160)
       ....
```

I was able to reproduce this with 2.x version of Yasson, but I have also verified, that it is no longer happening in version 3.0.0-RC1. 3.0.0-RC1 is using newer version of the JSON-P implementation.
