### ISSUE TITLE
Unable to make field final java.math.MathContext.roundingMode accessible

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#571]
**Describe the bug**
I get this error when trying to create json output of an instance of `java.math.MathContext`. 

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final java.math.RoundingMode java.math.MathContext.roundingMode accessible: module java.base does not "opens java.math" to unnamed module @4dca0ecd
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
	at org.eclipse.yasson.internal.model.PropertyValuePropagation.lambda$overrideAccessible$2(PropertyValuePropagation.java:153) ~[yasson-1.0.9.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at org.eclipse.yasson.internal.model.PropertyValuePropagation.overrideAccessible(PropertyValuePropagation.java:152) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.model.PropertyValuePropagation.isFieldVisible(PropertyValuePropagation.java:127) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.model.PropertyValuePropagation.initReadable(PropertyValuePropagation.java:94) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.model.PropertyValuePropagation.<init>(PropertyValuePropagation.java:80) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.model.ReflectionPropagation.<init>(ReflectionPropagation.java:39) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:134) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.ClassParser.lambda$parseProperties$0(ClassParser.java:71) ~[yasson-1.0.9.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:72) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:97) ~[yasson-1.0.9.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:81) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:65) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:107) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:125) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:121) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:69) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:107) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:125) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:121) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:69) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:107) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:125) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializeItem(AbstractContainerSerializer.java:194) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.MapToObjectSerializer.serializeContainer(MapToObjectSerializer.java:99) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.MapSerializer.serializeInternal(MapSerializer.java:156) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.MapSerializer.serializeInternal(MapSerializer.java:27) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:107) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:125) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:121) ~[yasson-1.0.9.jar:?]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:69) ~[yasson-1.0.9.jar:?]
	... 79 more
```

**To Reproduce**
Steps to reproduce the bug

**Expected behavior**
To be able to (de)serialize `java.math.MathContext`.

**System information:**
 - OS: Mac
 - Java Version: 17
 - Yasson Version: 1.0.9

**Comment by jbescos** [comment]
Could you provide a reproducer please?.

**Comment by nimo23** [comment]
@jbescos Here is the test case leading to this exception:

import static org.junit.jupiter.api.Assertions.assertNotNull;

```
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;

import javax.json.bind.JsonbBuilder;
import javax.json.bind.JsonbConfig;
import javax.json.bind.config.PropertyVisibilityStrategy;

import org.junit.jupiter.api.Test;

class BigDecimalJsonTest {

	public static class NumberText {

		private final BigDecimal number;
		private final MathContext mathContext;

		public NumberText(BigDecimal number, MathContext mathContext) {
			this.number = number;
			this.mathContext = mathContext;
		}

		public BigDecimal getNumber() {
			return number;
		}

		public MathContext getMathContext() {
			return mathContext;
		}
	}

	public static final class PrivateVisibilityStrategy implements PropertyVisibilityStrategy {
		@Override
		public boolean isVisible(Field field) {
			return true;
		}

		@Override
		public boolean isVisible(Method method) {
			return method.isAnnotationPresent(javax.json.bind.annotation.JsonbProperty.class);
		}
	}

	@Test
	final void testRestrictedNumber() {
		var mathContext = new MathContext(32, RoundingMode.HALF_UP);
		var numberText = new NumberText(BigDecimal.valueOf(5.3), mathContext);

		var json = toJson(numberText);
		System.out.println(json);
		assertNotNull(json);
	}

	public static String toJson(Object object) {
		try (var jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(true)
				.withNullValues(true)
				// using "PrivateVisibilityStrategy" leads to an exception
				.withPropertyVisibilityStrategy(new PrivateVisibilityStrategy()))) {
			return jsonb.toJson(object);
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}

}
```


I found the reason for this exception: 
I am using the `PrivateVisibilityStrategy` which leads to this exception. However, it's not very convenient to turn this off because in my case `BigDecimalJson` is just a property of another class hierarchy where I need the `PrivateVisibilityStrategy`. So if I disable it just because of `MathContext`, then the `PrivateVisibilityStrategy` for all other properties within the class hierarchy will also be disabled.

**Comment by jbescos** [comment]
I think the issue is that java.math module is not opened to java.base module, but you can explicitly open it with this JVM argument:
`--add-opens java.base/java.math=ALL-UNNAMED`

**Comment by Verdent** [comment]
`MathContext` is not supported by Yasson currently. If you need this to be serialized/deserialized properly, please create your own custom Serializer/Deserializer for it.
