### ISSUE TITLE
Deceptive exception: Cannot serialize java.time.Instant, IllegalAccessException: class is not public

### ISSUE THREAD

**Issue by hontvari** [eclipse-ee4j/yasson#582]
When serializing a class with an Instant field, I get an exception:
Caused by: java.lang.IllegalAccessException: class is not public: .../java.time.Instant/getField, from public Lookup
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:955)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:3882)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkField(MethodHandles.java:3832)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectFieldCommon(MethodHandles.java:4045)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectFieldNoSecurityManager(MethodHandles.java:4040)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3504)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectGetter(MethodHandles.java:3455)
	at org.eclipse.yasson.internal.model.PropertyModel.createReadHandle(PropertyModel.java:518)
	... 35 common frames omitted

It is not that the Instant class is not public, neither the return value or parameter type of getField, but the class containing the Instant field.

**System information:**
 - Java Version: 17.0.5
 - Yasson Version: 3.0.2

**Comment by Degubi** [comment]
Using this code:

```java
    public static void main( String[] args ) throws Exception {
        var jsonb = JsonbBuilder.create();
        var test = new Test(Instant.now());

        jsonb.toJson(test);
    }

    private static class Test {

        public final Instant testField;

        @JsonbCreator
        public Test(@JsonbProperty("testField") Instant testField) {
            this.testField = testField;
        }
    }
```

I got an error like this:

```
Exception in thread "main" jakarta.json.bind.JsonbException: Error accessing field 'testField' declared in 'class asd.Main$Test'
```

Which I think now looks correct given that the class is private
