### ISSUE TITLE
JsonGenerationException: not valid in current context IN_OBJECT

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#613]
**Describe the bug**
I have a custom `JsonbSerializer`. The following code works:

```
public final class NumberWrapperSerializer implements JsonbSerializer<NumberWrapper> {

  @Override
  public void serialize(NumberWrapper numberWrapper, JsonGenerator generator, SerializationContext ctx) {
	generator.writeStartObject();
	var number = numberWrapper.getValue();
	if (number instanceof Double doubleNum) {
		generator.write("value", doubleNum.isNaN() || doubleNum.isInfinite() ? null : doubleNum);
	}
	generator.writeEnd();
  }
}
```

The json output:

```
..
"myNum": {
	"value": 5.500000
},
..
```

However, what I want to achieve is to write the value directly to myNum:

```
..
"myNum": 5.500000,
..
```

So I adapt `NumberWrapperSerializer` as follows:

```
@Override
public void serialize(NumberWrapper numberWrapper, JsonGenerator generator, SerializationContext ctx) {
	generator.writeStartObject();
	var number = numberWrapper.getValue();
	if (number instanceof Double doubleNum) {
		// the stacktrace points to this line:
		generator.write(doubleNum.isNaN() || doubleNum.isInfinite() ? null : doubleNum);
	}
	generator.writeEnd();
}
```

But then I get the following stacktrace:

```
Caused by: jakarta.json.stream.JsonGenerationException: Illegal method during JSON generation, not valid in current context IN_OBJECT
	at org.eclipse.parsson//org.eclipse.parsson.JsonGeneratorImpl.checkContextForValue(JsonGeneratorImpl.java:406)
	at org.eclipse.parsson//org.eclipse.parsson.JsonGeneratorImpl.write(JsonGeneratorImpl.java:412)
	at org.eclipse.parsson//org.eclipse.parsson.JsonPrettyGeneratorImpl.write(JsonPrettyGeneratorImpl.java:27)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.YassonGenerator.write(YassonGenerator.java:168)
	at deployment.mytest.war//my.util.NumberWrapperSerializer.serialize(NumberWrapperSerializer.java:22)
	at deployment.mytest.war//my.util.NumberWrapperSerializer.serialize(NumberWrapperSerializer.java:1)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.UserDefinedSerializer.serialize(UserDefinedSerializer.java:35)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.RecursionChecker.serialize(RecursionChecker.java:38)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.KeyWriter.serialize(KeyWriter.java:41)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.NullSerializer.serialize(NullSerializer.java:67)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.MapSerializer$StringKeyMapSerializer.lambda$serialize$0(MapSerializer.java:109)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.MapSerializer$StringKeyMapSerializer.serialize(MapSerializer.java:107)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.KeyWriter.serialize(KeyWriter.java:41)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.NullVisibilitySwitcher.serialize(NullVisibilitySwitcher.java:40)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.NullSerializer.serialize(NullSerializer.java:67)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.ValueGetterSerializer.serialize(ValueGetterSerializer.java:43)
	at deployment.mytest.war//org.eclipse.yasson.internal.serializer.ObjectSerializer.lambda$serialize$0(ObjectSerializer.java:41)
	... 98 more
```

If I use this:

```
@Override
public void serialize(NumberWrapper numberWrapper, JsonGenerator generator, SerializationContext ctx) {
	var number = numberWrapper.getDelegate();
	if (number instanceof Double doubleNum) {
		// the stacktrace points to this line:
		generator.write(doubleNum.isNaN() || doubleNum.isInfinite() ? null : doubleNum);
	}
}
```

then the following stacktrace happens:

```
Caused by: jakarta.json.stream.JsonGenerationException: Illegal method during JSON generation, not valid in current context IN_FIELD
	at org.eclipse.parsson//org.eclipse.parsson.JsonGeneratorImpl.writeKey(JsonGeneratorImpl.java:459)
	at org.eclipse.parsson//org.eclipse.parsson.JsonPrettyGeneratorImpl.writeKey(JsonPrettyGeneratorImpl.java:27)
```

**Expected behavior**
No errors.

**System information:**
 - OS: Mac OS
 - Java Version: 17
 - Yasson Version: yasson-3.0.3.jar

**Comment by redmitry** [comment]
Hi,

To be fair I do not see the problem.

```java
generator.writeStartObject();
generator.write("value", doubleNum.isNaN() || doubleNum.isInfinite() ? null : doubleNum);
generator.writeEnd();
```
generates;
```json
"myNum": {
	"value": 5.500000
}
```
is exactly what you are writing.

```java
generator.writeStartObject();
generator.write(doubleNum.isNaN() || doubleNum.isInfinite() ? null : doubleNum);
generator.writeEnd();
```
What you suppose to write?
```json
{ 5.500000 }
```
???
This is the invalid JSON and what is reported by the parser:
>Illegal method during JSON generation, not valid in current context IN_FIELD

Just write the property if this is what you want:  
`generator.write("value", doubleNum.isNaN() || doubleNum.isInfinite() ? null : doubleNum);`

>..
>"myNum": 5.500000,
>..

Kind regards,

D.

**Comment by redmitry** [comment]
Hi,
First to mention, you can't just write null, but rather call writeNull() method.
Also since we are writing the value we always have to write something (null?).
My guess:
```java
@Override
public void serialize(NumberWrapper numberWrapper, JsonGenerator generator, SerializationContext ctx) {
	var number = numberWrapper.getDelegate();
	if (number instanceof Double doubleNum) {
		// the stacktrace points to this line:
                if (doubleNum.isNaN() && doubleNum.isInfinite()) {
                        generator.writeNull();
                } else {
                        generator.write(doubleNum);
                }
	} else {
	        generator.writeNull();
        }
}
