### ISSUE TITLE
SimpleTest fails when using a different JSON-P impl

### ISSUE THREAD

**Issue by aguibert** [eclipse-ee4j/yasson#96]
Yasson should work with any spec compliant JSON-P 1.1 implementaiton.  If I try to use Yasson with Apache Johnzon, serializing a simple POJO with a String attribute fails with the following error:

```
javax.json.stream.JsonGenerationException: write(param) is only valid in arrays
	at org.apache.johnzon.core.JsonGeneratorImpl.checkArray(JsonGeneratorImpl.java:614)
	at org.apache.johnzon.core.JsonGeneratorImpl.write(JsonGeneratorImpl.java:378)
	at org.eclipse.yasson.internal.serializer.StringTypeSerializer.serialize(StringTypeSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.StringTypeSerializer.serialize(StringTypeSerializer.java:1)
	at org.eclipse.yasson.internal.serializer.AbstractValueTypeSerializer.serialize(AbstractValueTypeSerializer.java:51)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:94)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:119)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:75)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at org.eclipse.yasson.SimpleTest.testSimpleSerialize(SimpleTest.java:48)
        <rest of the stack is junit runner>
```

This used to work with Yasson 1.0, and seems to have regressed in Yasson 1.0.1.

This can be easily reproduced by changing the JSON-P dependency from `org.glassfish:javax.json` to `org.apache.johnzon:johnzon-core:1.1.5` and running org.eclipse.yasson.SimpleTest.

**Comment by aguibert** [comment]
It seems the regression was caused by this commit:
https://github.com/eclipse/yasson/commit/d07215438772598407ba9842514e0030b403faf4#diff-44d72b506105258cffab226412abc88b

Looks like if we have the class:
```java
public class Data {
  public String foo = "bar";
}
```
Then Yasson will write this by effectively doing:
`generator.writeStartObject​().write("foo").write("bar).writeEndObject​()`

Johnzon seems to interpret the JSON-P spec as requiring:
`generator.writeStartObject​().write("foo", "bar").writeEndObject​()`
and asserts that the single-write operations such as `write("foo")` are only allowed in the context of JSON arrays.

So the question is: 
Should `write("key").write("value")` be allowed by the spec?  The javadoc states:
> JsonGenerator#write​(String value)
> Writes the specified value as a JSON string value within the current array, field or root context.

**Comment by aguibert** [comment]
I've opened an issue on the JSON-P spec for clarificaiton.  Based on the outcome of that issue, this will either be a no-op (Johnzon would need to change) or this would be a valid bug and Yasson would need to change.

**Comment by m0mus** [comment]
I commented on JSON-P issue you created. The idea was to allow write(param) method to be used in JSON objects, but we forgot to change the spec. I'll contact Johnzon folks and try to convince them logging a warning in this case instead of throwing an exception.

**Comment by aguibert** [comment]
@bravehorsie yea this can be closed, since the required action is by the Johnzon code, not the Yasson code
